version: '3'
services:
  next:
    build: ./docker/next
    volumes:
      - ./frontend:/usr/app 
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro  
    ports:
      - "3000:3000"
    command: "npm run dev"
  express:
    build: ./docker/express
    volumes:
      - ./backend:/usr/app 
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro  
    ports:
      - "4000:4000"
    command: >
        bash -c "npm install &&
        npm install nodemon -g &&
        nodemon src/server.ts"
  db:
    build: ./docker/db
    volumes:
      - ./src/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./backend/.env
